vim.cmd("set clipboard+=unnamedplus")
vim.opt.encoding = "utf-8"
vim.opt.fileencoding = "utf-8"
vim.opt.ignorecase = true
vim.opt.laststatus = 2
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.shiftwidth = 4
vim.opt.showtabline = 2
vim.opt.startofline = true
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.title = true
